##############################
# Netlify configuration file #
##############################

# List of Build plugins
[[plugins]]
# Use the current plugin in builds for testing and debugging.
# Local path to the plugin.
package = "."
  # Plugin configuration
  [plugins.inputs]
  templates_dir = "test/sample/resoc-templates"
  slug_to_image_data_function = "test/sample/slug-to-image-data.js"
  slug_to_image_data_mapping_file = "test/sample/resoc-storage.json"

[build]
  command = "npm run build:sample"

[build.environment]
NODE_VERSION = "12.18.0"

[functions]
  included_files = [ "test/sample/resoc-template/**" ]
