##############################
# Netlify configuration file #
##############################

# List of Build plugins
[[plugins]]
# Use the current plugin in builds for testing and debugging.
# Local path to the plugin.
package = "."
  # Plugin configuration
  [plugins.inputs]
  templates_dir = "test/sample/resoc-templates"
  slug_to_image_data = "test/sample/slug-to-image-data"

[build]
# Dummy build command
command = "echo onBuild"

[build.environment]
NODE_VERSION = "12.18.0"

[functions]
  included_files = [ "test/sample/resoc-template/**" ]
